# -*- coding: utf-8 -*-
"""finds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IWYCbHqtywyLra6XQQUBSmsFpn_SeThS
"""

import csv
with open("/findsss.csv") as finds:
  reader=csv.reader(finds)
  data=list(reader)

data

h=['0','0','0','0','0','0']
for row in data:
  if row[-1]=='Yes':
    j=0
    for col in row:
      if col!='Yes':
        if col!=h[j] and h[j]=='0':
          h[j]=col
        elif col!=h[j] and h[j]!='0':
          h[j]='?'
          print(col)
        j=j+1

h

